version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: 'personaggiGioco'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: