version: '3.8'
services:
  app:
    image: 063176071466.dkr.ecr.eu-west-1.amazonaws.com/atf-gioco-1-2023-02:raffaele5
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    environment:
      spring.datasource.url: 'jdbc:mysql://mysqldb:3306/personaggiGioco'
      spring.datasource.driver-class-name: 'com.mysql.cj.jdbc.Driver'
      spring.datasource.username: 'user'
      spring.datasource.password: 'password'
      spring.jpa.hibernate.ddl.auto: 'update'
    networks:
      - 'mynetwork'

  mysqldb:
    image: mysql:latest
    container_name: mysqldb2
    environment:
      MYSQL_DATABASE: 'personaggiGioco'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - 'mynetwork'
volumes:
  my-db:

networks:
  mynetwork: