FROM openjdk:11
COPY target/api-personaggi-gioco-0.0.1-SNAPSHOT.jar /usr/local/api-personaggi-gioco-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/usr/local/api-personaggi-gioco-0.0.1-SNAPSHOT.jar"]